"""Import provenance manifest tests."""

from datetime import UTC, datetime
from pathlib import Path

from app.data.manifest import build_import_manifest
from app.data.registry import SourceRegistry

ROOT = Path(__file__).parents[3]


def test_manifest_records_checksum_rights_and_metadata(tmp_path: Path) -> None:
    source_file = tmp_path / "fictional.csv"
    source_file.write_text("x,y\n1,2\n", encoding="utf-8")
    source = SourceRegistry.load(ROOT / "data" / "sources.yml").get(
        "synthetic_playerpulse"
    )
    timestamp = datetime(2026, 7, 21, tzinfo=UTC)

    manifest = build_import_manifest(
        source=source,
        source_match_id="synthetic-match-001",
        files=[("tracking", source_file)],
        imported_at_utc=timestamp,
    )

    assert manifest.imported_at_utc == timestamp
    assert manifest.is_synthetic
    assert manifest.files[0].original_name == "fictional.csv"
    assert manifest.files[0].size_bytes == source_file.stat().st_size
    assert len(manifest.files[0].sha256) == 64
    assert manifest.rights_snapshot["attribution"] == "Generated by PlayerPulse"
