"""Idempotent deterministic demo persistence."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from sqlalchemy.orm import Session

from app.data.processing import ProcessingResult, process_synthetic_demo
from app.db.models import DatasetImport, Match, Player
from app.repositories.analytics import AnalyticsRepository
from app.repositories.datasets import DatasetRepository
from app.repositories.matches import MatchRepository
from app.repositories.teams import TeamPlayerRepository


@dataclass(frozen=True)
class DemoCreationResult:
    """Stored demo identities and freshly generated analytical tables."""

    dataset_import: DatasetImport
    match: Match
    players: list[Player]
    processing: ProcessingResult
    created: bool


def _metric_values(processing: ProcessingResult, player: Player) -> dict[str, object]:
    movement = processing.tables["movement_features"]
    player_rows = movement[movement["player_id"] == player.external_id]
    valid_speed = player_rows["speed_mps"].dropna()
    playing_seconds = (
        player_rows.groupby("period")["timestamp_seconds"]
        .agg(lambda values: values.max() - values.min())
        .sum()
    )
    sprint_rows = processing.tables["sprints"]
    player_sprints = sprint_rows[sprint_rows["player_id"] == player.external_id]
    sprint_counts = player_sprints.groupby("period").size()
    sprint_change = None
    if 1 in sprint_counts and int(sprint_counts.loc[1]) > 0:
        first_count = int(sprint_counts.loc[1])
        second_count = int(sprint_counts.get(2, 0))
        sprint_change = 100 * (second_count - first_count) / first_count
    recoveries = (
        player_sprints.sort_values(["period", "start_seconds"])
        .groupby("period")["start_seconds"]
        .diff()
    )
    period_speed = player_rows.groupby("period")["speed_mps"].mean()
    speed_change = None
    if len(period_speed) == 2 and float(period_speed.iloc[0]) > 0:
        speed_change = (
            100
            * (float(period_speed.iloc[1]) - float(period_speed.iloc[0]))
            / float(period_speed.iloc[0])
        )
    total_distance = float(player_rows["step_distance_m"].sum())
    playing_minutes = float(playing_seconds) / 60
    return {
        "playing_minutes": playing_minutes,
        "total_distance_m": total_distance,
        "distance_per_minute": total_distance / playing_minutes
        if playing_minutes
        else 0,
        "average_speed_mps": float(valid_speed.mean()) if not valid_speed.empty else 0,
        "max_speed_mps": float(valid_speed.max()) if not valid_speed.empty else 0,
        "high_speed_distance_m": float(
            player_rows.loc[player_rows["speed_mps"] >= 5.5, "step_distance_m"].sum()
        ),
        "sprint_count": len(player_sprints),
        "sprint_distance_m": float(player_sprints["distance_m"].sum())
        if not player_sprints.empty
        else 0,
        "median_sprint_recovery_seconds": (
            float(recoveries.median()) if recoveries.notna().any() else None
        ),
        "acceleration_count": int((player_rows["acceleration_mps2"] >= 2).sum()),
        "deceleration_count": int((player_rows["deceleration_mps2"] >= 2).sum()),
        "second_half_speed_change_pct": speed_change,
        "late_match_sprint_change_pct": sprint_change,
        "late_match_distance_change_pct": None,
        "pass_accuracy_change_pct": None,
        "pressure_change_pct": None,
        "possession_loss_change": None,
        "workload_vs_baseline_zscore": 0.0,
        "data_quality_score": processing.quality.quality_score / 100,
        "baseline_type": "match_only",
        "baseline_confidence": 0.4,
        "supported_event_metrics": True,
        "feature_version": "features-v1",
    }


def create_demo_dataset(
    session: Session, *, seed: int = 20_260_720, period_duration_s: int = 180
) -> DemoCreationResult:
    """Generate and store the same fictional match without duplicate records."""
    checksum = hashlib.sha256(f"playerpulse-demo:{seed}:v1".encode()).hexdigest()
    datasets = DatasetRepository(session)
    existing_import = datasets.get_by_checksum(checksum)
    dataset_import = datasets.create_if_absent(
        provider="PlayerPulse",
        source_registry_id="synthetic_playerpulse",
        checksum=checksum,
        rights_snapshot={
            "usage_status": "project_owned_synthetic",
            "attribution": "Generated by PlayerPulse",
        },
        manifest=[],
        is_synthetic=True,
    )
    teams = TeamPlayerRepository(session)
    home = teams.get_or_create_team(
        source="synthetic_playerpulse", external_id="home", name="Synthetic Home"
    )
    away = teams.get_or_create_team(
        source="synthetic_playerpulse", external_id="away", name="Synthetic Away"
    )
    processing = process_synthetic_demo(seed=seed, period_duration_s=period_duration_s)
    player_records: list[Player] = []
    for player_id in sorted(processing.tables["tracking"]["player_id"].unique()):
        team = home if str(player_id).startswith("home") else away
        number = int(str(player_id).split("-")[-1])
        player_records.append(
            teams.get_or_create_player(
                team=team,
                source="synthetic_playerpulse",
                external_id=str(player_id),
                name=f"Synthetic Player {number:02d}",
                position="Goalkeeper" if number == 1 else "Outfield",
            )
        )
    matches = MatchRepository(session)
    match = matches.create_if_absent(
        source="synthetic_playerpulse",
        external_id="synthetic-match-001",
        home_team_id=home.id,
        away_team_id=away.id,
        competition="Fictional Demonstration",
        dataset_import_id=dataset_import.id,
        is_synthetic=True,
        processing_status="complete",
    )
    analytics = AnalyticsRepository(session)
    for player in player_records:
        analytics.upsert_metric(
            match_id=match.id,
            player_id=player.id,
            **_metric_values(processing, player),
        )
    dataset_import.import_status = "complete"
    session.commit()
    return DemoCreationResult(
        dataset_import=dataset_import,
        match=match,
        players=player_records,
        processing=processing,
        created=existing_import is None,
    )
